import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight } from "lucide-react";
import { WorkGallery, ReadingProgress } from "@/components/proof-experience";
import { Action, ExperienceStrip, Testimonials, FinalInvitation, coachingPath } from "@/components/proof-shared";
import styles from "@/components/proof-pages.module.css";

export const metadata: Metadata = {
  title: "Proof of Work | Communication Coaching in Practice",
  description: "Explore The Speech Factory’s communication coaching in practice: workshop moments, participant experiences and the people behind the work.",
  alternates: { canonical: "https://thespeechfactory.org/proof-of-work" },
  openGraph: { title: "The work. The people. The difference. | The Speech Factory", description: "Communication coaching, seen in practice.", images: [{ url: "/images/team-training.webp", width: 1200, height: 800, alt: "The Speech Factory workshop in action" }] },
};
export default function ProofPage(){return <main className={styles.page}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: "{\"@context\":\"https://schema.org\",\"@type\":\"WebPage\",\"name\":\"Proof of Work\",\"url\":\"https://thespeechfactory.org/proof-of-work\",\"isPartOf\":{\"@type\":\"WebSite\",\"name\":\"The Speech Factory\",\"url\":\"https://thespeechfactory.org/\"}}" }}/><ReadingProgress/>
  <section className={styles.proofHero}>
    <div className={`${styles.wrap} ${styles.heroGrid}`}>
      <div className={styles.heroCopy}><p className={styles.eyebrow}><span/> Proof of work</p><h1>The work.<br/>The people.<br/><em>The difference.</em></h1><p>Communication changes when you put it into practice. Here’s a closer look at the rooms, the conversations and the people behind our work.</p><a href="#selected-work" className={styles.heroExplore}>See the work <ArrowDown size={19}/></a><div className={styles.heroFootnote}><span>THE SPEECH FACTORY</span><span>Clarity. Confidence. Impact.</span></div></div>
      <div className={styles.heroCollage}><div className={styles.heroPhoto}><Image src="/images/team-training.webp" alt="Workshop participants practising communication together at The Speech Factory" fill priority sizes="(max-width: 900px) 100vw, 52vw"/><div className={styles.photoCaption}><span>01 / Inside the work</span><span>Practice, in good company.</span></div></div><div className={styles.heroInset}><Image src="/images/coach-session.webp" alt="Jeremiah speaking during a live coaching session" fill sizes="(max-width: 700px) 35vw, 18vw"/></div><div className={styles.heroStamp}><span>Built through</span><strong>practice.</strong><svg viewBox="0 0 130 28" aria-hidden="true"><path d="M2 15h10l6-9 8 17 8-21 8 24 8-17 8 10 8-4h12l7-10 8 16 7-10 9 5h17"/></svg></div></div>
    </div>
  </section>
  <nav className={styles.chapterNav} aria-label="Proof of Work chapters"><div className={styles.wrap}><span>A closer look</span><a href="#selected-work">01 / Selected work</a><a href="#voices">02 / In their words</a><a href="#in-practice">03 / In the room</a><a href="#your-proof">Your next step <ArrowUpRight size={15}/></a></div></nav>
  <section className={`${styles.wrap} ${styles.proofNumbers}`} aria-label="Experience behind our work"><div><strong>2,000<span>+</span></strong><p>Students and professionals trained</p></div><div><strong>10<span>+ years</span></strong><p>Our founder’s international speaking and coaching experience</p></div><div><strong>2019</strong><p>WUDC public speaking title won by founder Jeremiah Kobby Sekyi</p></div></section>
  <ExperienceStrip/>
  <section id="selected-work" className={`${styles.wrap} ${styles.section}`}>
    <div className={styles.sectionHeading}><div><p className={styles.eyebrow}>01 / Selected work</p><h2>Different rooms.<br/><em>The same purpose.</em></h2></div><p>From a first presentation to a high-stakes professional conversation, our work is grounded in one thing: helping people make themselves understood.</p></div>
    <div className={styles.workGrid}>
      <article className={styles.workCard} data-reveal><Link href={`${coachingPath}#corporate-training`} className={styles.workImage} aria-label="Explore executive and corporate communication training"><Image src="/images/group-coaching.webp" alt="A facilitated communication exercise with a group of professionals" fill sizes="(max-width: 700px) 100vw, 55vw"/><span className={styles.imageTag}>For teams & organisations</span><span className={styles.imageArrow}><ArrowUpRight/></span></Link><div className={styles.workTitle}><span>01</span><h3>Executive & Corporate<br/>Communication Training</h3></div><p>Practical communication, public speaking and presentation development. Real workplace scenarios, shared practice and feedback that teams can take back to work.</p><div className={styles.skillTags}><span>Leadership</span><span>Presentations</span><span>Team practice</span></div></article>
      <article className={`${styles.workCard} ${styles.workOffset}`} data-reveal><Link href={`${coachingPath}#executive-coaching`} className={styles.workImage} aria-label="Explore private public speaking and executive communication coaching"><Image src="/images/executive-coaching.webp" alt="Jeremiah preparing at a desk for professional communication work" fill sizes="(max-width: 700px) 100vw, 40vw"/><span className={styles.imageTag}>For individuals & leaders</span><span className={styles.imageArrow}><ArrowUpRight/></span></Link><div className={styles.workTitle}><span>02</span><h3>Private Public Speaking & Executive Communication Coaching</h3></div><p>Individual attention, built around a real goal. Structure your ideas, strengthen your delivery and rehearse the conversations that matter to you.</p><div className={styles.skillTags}><span>Clarity</span><span>Confidence</span><span>Executive presence</span></div></article>
    </div>
    <article className={styles.workWide} data-reveal><div className={styles.widePhoto}><Image src="/images/workshop-speaker.webp" alt="A participant addressing fellow attendees during a practical workshop" fill sizes="(max-width: 700px) 100vw, 50vw"/></div><div><p className={styles.eyebrow}>03 / Learning by doing</p><h3>Communication Workshops<br/>& Masterclasses</h3><p>A room becomes a rehearsal space. Participants test ideas, practise delivery and learn from one another through practical, high-participation sessions.</p><blockquote>“You shifted all our universes with your guidance today. Spectacular.”<cite>Olivia J. · Seismic team workshop participant</cite></blockquote><Action href={`${coachingPath}#corporate-training`} secondary>Explore workshops for your team</Action></div></article>
  </section>
  <section id="voices" className={styles.voices}><div className={styles.wrap}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>02 / In their words</p><h2>The difference,<br/><em>as they describe it.</em></h2></div><p>Confidence is personal. So are the stories of the people who have worked with us.</p></div><Testimonials/></div></section>
  <section id="in-practice" className={`${styles.wrap} ${styles.section}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>03 / In the room</p><h2>Less theory.<br/><em>More lived experience.</em></h2></div><p>A few moments from our workshops and behind the scenes. Real people, actively doing the work.</p></div><WorkGallery/></section>
  <section id="your-proof" className={styles.bridge}><div className={`${styles.wrap} ${styles.bridgeGrid}`}><div className={styles.bridgeImage}><Image src="/images/coach-stage.jpeg" alt="Jeremiah delivering a speech from a podium" fill sizes="(max-width: 800px) 100vw, 40vw"/><span>What this can look like for you</span></div><div><p className={styles.eyebrow}>From their story to yours</p><h2>Ready to build<br/><em>your own proof?</em></h2><p>Our coaching and training programmes help professionals, leaders and ambitious communicators develop the clarity, confidence and presence to perform when communication matters.</p><div className={styles.bridgeOptions}><span>A presentation worth remembering.</span><span>A meeting where your ideas land.</span><span>A voice you can trust under pressure.</span></div><Action href={coachingPath} event="proof_to_service_click">Explore Communication Coaching</Action><Action href="/book" secondary event="communication_consultation_click">Work With The Speech Factory</Action></div></div></section>
  <FinalInvitation/>
</main>;}
