import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, CalendarDays, Mic2, BookOpen, ClipboardCheck, MessagesSquare, Award, Check, Plus } from "lucide-react";
import { PilotSignup } from "@/components/pilot-signup";
import styles from "@/components/pilot.module.css";
export const metadata:Metadata={title:"Public Speaking Academy · Communication Excellence Programme · Class of 2027",description:"Three months of practical communication coaching, weekly live sessions, tasks, feedback and resources. Join The Speech Factory’s Public Speaking Academy. The Communication Excellence Programme, Class of 2027, offers three months of group coaching starting in January."};
const inclusions=[
 [CalendarDays,"Weekly live sessions","Learn a communication skill, see it modelled and put it into practice. Sessions combine practical teaching, discussion and speaking exercises."],
 [Mic2,"Practical coaching","Speak, receive guidance and try again. Work on your message, structure, delivery and audience connection through coached practice."],
 [ClipboardCheck,"Weekly tasks","A focused exercise between sessions helps you use what you learn. Expect speech outlines, short recordings, reflection and real-world speaking practice."],
 [MessagesSquare,"Monthly projects & feedback","Bring the month’s skills together in a more developed speaking task. Use feedback to revise your work and identify what to practise next."],
 [BookOpen,"Resources you can use","Speech structures, preparation checklists, practice prompts, worksheets and examples to support your work during the programme."],
 [Award,"A completion certificate","Mark the work you have put in with a TSF completion certificate, based on participation and completion of the required programme tasks."],
] as const;
const journey=[
 {month:"01",label:"Foundations & confidence",title:"Find your starting point.",copy:"Build awareness of your speaking habits. Learn to structure ideas, introduce yourself, manage nerves and connect with an audience.",task:"A personal introduction or story, refined through practice and feedback."},
 {month:"02",label:"Clarity & presentations",title:"Make your ideas easy to follow.",copy:"Choose relevant information, organise your message and explain ideas clearly. Practise informative speaking and presentations rooted in your work or interests.",task:"An informative talk or presentation with a clear message, examples and takeaway."},
 {month:"03",label:"Influence & real-world delivery",title:"Say it with purpose.",copy:"Strengthen persuasion, storytelling and your response to questions. Rehearse the professional situations where you want your voice to have more impact.",task:"A final speaking showcase and reflection on your progress and next steps."},
];
const questions=[
 ["Who is the programme for?","Professionals, founders, students and emerging leaders who want to communicate with more clarity, confidence and impact. You do not need to be an experienced speaker. What matters is a willingness to practise, participate and respond to feedback."],
 ["What does the programme cost?","The programme fee is US$300 for the full three-month programme. Registering interest and booking a consultation do not take payment or reserve a place. We will explain the enrolment process and payment arrangements before you commit."],
 ["When are the weekly sessions?","The programme starts in January 2027. The exact start date, weekly session day, time and duration will be confirmed before enrolment. Tell us your time zone and availability in the form so the team can discuss whether the schedule will work for you."],
 ["How much practice should I expect?","Plan to attend the weekly live sessions and set aside time between sessions for a focused task. Each month also includes a larger speaking project. The task brief and deadlines will explain what to prepare; the full workload will be clarified before enrolment."],
 ["Will I receive individual feedback?","Feedback is part of the practical coaching and monthly tasks. Coaches will help you identify useful changes to your structure, delivery and audience connection. The precise feedback format will be explained during programme onboarding."],
 ["Who leads the programme?","The programme is delivered by The Speech Factory coaching team, led by founder Jeremiah Kobby Sekyi. Jeremiah will be involved throughout the programme, alongside excellent professional coaches with various areas of expertise supporting your journey. The facilitator assignments and session schedule will be confirmed before enrolment."],
 ["How do I earn the certificate?","The certificate recognises completion of the TSF programme, including required participation and tasks. The attendance and submission requirements will be shared before enrolment. It is a TSF completion certificate, not an accredited professional qualification."],
 ["What if I need help before January?","Tell us in the registration form. You can flag interview preparation, an upcoming presentation, a speech or practical coaching. We can discuss earlier support during your consultation. Separate coaching is subject to availability and its own agreed fee."],
 ["What happens after I register?","Your details are saved privately for The Speech Factory team. You will then be directed to our booking calendar to choose a consultation. We will discuss your goals, availability and next steps before you decide whether to enrol."],
];
export default function PilotPage(){return <main className={styles.page}>
 <section className={styles.hero}><div className={styles.heroInner}><div className={styles.heroCopy}><Link href="/" className={styles.breadcrumb}>The Speech Factory / Public Speaking Academy</Link><p className={styles.eyebrow}><span/> Communication Excellence Programme · Class of 2027</p><h1>Your ideas<br/>deserve a<br/><em>stronger voice.</em></h1><p>Our Public Speaking Academy is here. Our first programme, the Communication Excellence Programme, is a three-month group coaching experience starting in January 2027. Make progress through practice, feedback and a community that grows with you. Build the way you speak, present and connect.</p><a href="#register" className={styles.button}>Register your interest <ArrowUpRight size={18}/></a><a href="#inside" className={styles.heroSecondary}>Take a look inside <ArrowDown size={16}/></a></div><div className={styles.heroMedia}><Image src="/images/workshop-speaker.webp" alt="A participant putting her communication skills into practice at a Speech Factory workshop" fill priority sizes="(max-width: 800px) 100vw, 52vw"/><div className={styles.heroNote}><span>Speak. Practise. Refine.</span><strong>Then do it again.</strong></div><div className={styles.heroCaption}>Real practice. Real people. The Speech Factory.</div></div></div></section>
 <div className={styles.facts}><div><span>WHEN</span><strong>January 2027</strong></div><div><span>COMMITMENT</span><strong>Three months</strong></div><div><span>WHERE</span><strong>Online, together</strong></div><div><span>PROGRAMME FEE · DISCOUNTED</span><strong>US$300 <small>total</small></strong></div></div>
 <section className={`${styles.wrap} ${styles.development}`} aria-labelledby="development-heading"><div className={styles.developmentPhoto}><Image src="/images/team-training.webp" alt="A group communication training session with The Speech Factory" fill sizes="(max-width: 800px) 100vw, 42vw"/><span>From our workshops to your next chapter.</span></div><div className={styles.developmentCopy}><p className={styles.eyebrow}>The story behind our academy</p><h2 id="development-heading">An experience years in the making,<br/><em>now ready for you.</em></h2><p>Over several years, we have worked with professionals and executives from several Fortune 500 companies, alongside students and emerging leaders. That experience has given us a deep understanding of the challenges people face: finding confidence, organising ideas, explaining complex subjects, thinking under pressure and making their voice heard.</p><p>Through multiple workshops and practice with hundreds of professionals, we have tested and refined the approach behind our Public Speaking Academy. We know it works because we have seen people put it into practice. We have seen shy people find their confidence. We have seen clients land massive roles by nailing their interviews. But perhaps most importantly, we have seen our clients use their voice to influence the world around them for the better.</p><p>Our Public Speaking Academy brings that experience together with co-facilitators who combine public speaking mastery with subject matter expertise. You learn from coaches who understand both how to communicate and the contexts in which your communication needs to work.</p><p>The Class of 2027 begins with our three-month Communication Excellence Programme: structured group coaching with like-minded, ambitious individuals, purposeful practice and feedback that helps you move forward.</p><Link href="/proof-of-work" className={styles.textLink}>See the work behind the programme <ArrowUpRight size={18}/></Link></div></section>
 <section id="inside" className={`${styles.wrap} ${styles.section}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>More than a weekly call</p><h2>Our programme is structured<br/><em>to deliver tangible progress.</em></h2></div><p>The real work happens when you use your voice. This group coaching programme brings live learning, guided practice and clear next steps into one consistent routine.</p></div><div className={styles.inclusions}>{inclusions.map(([Icon,title,copy],i)=><article key={title} data-reveal><div><Icon size={27} strokeWidth={1.4}/><span>0{i+1}</span></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section className={styles.rhythm}><div className={styles.wrap}><div><p className={styles.eyebrow}>Your week, with intention</p><h2>Learn it live.<br/>Try it yourself.<br/><em>Bring it back better.</em></h2><p>The programme is built around active participation. Come ready to speak, listen, experiment and give others room to do the same.</p><a href="#register" className={styles.textLink}>Make space for your voice <ArrowUpRight size={18}/></a></div><ol>{[["01","Meet & learn","Join the live session. Explore a skill, see examples and ask questions."],["02","Speak & get coached","Try the skill in practice, with guidance on what to keep and what to change."],["03","Complete your weekly task","Apply the lesson through a focused speaking, preparation or reflection exercise."],["04","Reflect & repeat","Bring your learning forward. Each month, combine the skills in a larger project."]].map(([n,t,p])=><li key={n} data-reveal><span>{n}</span><div><h3>{t}</h3><p>{p}</p></div></li>)}</ol></div></section>
 <section className={`${styles.wrap} ${styles.section}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Your three-month journey</p><h2>Build the foundations.<br/><em>Then take them further.</em></h2></div><p>A progressive learning journey, with speaking tasks that connect the work to your own goals. The detailed calendar will be shared before enrolment.</p></div><div className={styles.journey}>{journey.map(j=><article key={j.month} data-reveal><span className={styles.month}>MONTH <b>{j.month}</b></span><p className={styles.eyebrow}>{j.label}</p><h3>{j.title}</h3><p>{j.copy}</p><div className={styles.task}><span>Monthly practice project</span><p>{j.task}</p></div></article>)}</div></section>
 <section className={styles.people}><div className={styles.peoplePhoto}><Image src="/images/group-coaching.webp" alt="Group members learning through discussion and live speaking practice" fill sizes="(max-width: 800px) 100vw, 50vw"/></div><div className={styles.peopleCopy}><p className={styles.eyebrow}>Progress in good company</p><h2>You don’t have to<br/><em>start confident.</em></h2><p>You need a place to practise and a reason to keep going. Bring the ideas you want to explain, the moments that make you nervous and the willingness to try again.</p><ul>{["Practise with people who are doing the work too.","Make mistakes, receive feedback and refine your approach.","Build skills you can carry into meetings, presentations and everyday conversations."].map(s=><li key={s}><Check size={18}/>{s}</li>)}</ul><Link href="/proof-of-work" className={styles.textLink}>See our coaching in practice <ArrowUpRight size={18}/></Link></div></section>
 <section className={`${styles.wrap} ${styles.practical}`}><div><p className={styles.eyebrow}>Before you sign up</p><h2>Important points to note</h2></div><div><p><strong>You will be committing to three intensive months, at a total cost of US$300.</strong> This includes live weekly sessions, practical coaching, weekly tasks, monthly projects, resources and a completion certificate as part of the programme. We are offering this programme at a discounted rate to ensure as many people as possible can access this crucial training.</p><p><strong>The exact calendar dates will depend on your availability.</strong> We’ll discuss the start date, session times, workload and enrolment terms with you before you commit. Completing this form is an expression of interest, with no payment taken.</p><p><strong>Need support sooner?</strong> Flag it below. We can discuss interview preparation, practice coaching or an upcoming speaking challenge separately.</p></div></section>
 <section id="register" className={styles.registerSection}><div className={styles.registerGrid}><div className={styles.registerIntro}><p className={styles.eyebrow}>Class of 2027 · Your next step</p><h2>Start with<br/><em>your story.</em></h2><p>Tell us where you are, what you want to work on and when you are ready to begin.</p><ol><li><span>01</span> Share your details and goals.</li><li><span>02</span> Choose a consultation time.</li><li><span>03</span> Discuss the right next step.</li></ol><div className={styles.registerContact}><span>Prefer to ask a question first?</span><a href="mailto:management@thespeechfactory.org">management@thespeechfactory.org</a></div></div><PilotSignup/></div></section>
 <section className={`${styles.wrap} ${styles.section} ${styles.faqSection}`}><div><p className={styles.eyebrow}>A little more clarity</p><h2>Have questions?<br/><em>We have got answers.</em></h2></div><div className={styles.faqs}>{questions.map(([q,a])=><details key={q}><summary><h3>{q}</h3><Plus size={20}/></summary><p>{a}</p></details>)}</div></section>
 </main>;}
