import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Check } from "lucide-react";
import { programmes } from "@/lib/content";

export function generateStaticParams() { return programmes.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const programme = programmes.find(item => item.slug === slug); return programme ? { title: programme.title, description: programme.short } : {}; }
export default async function ProgrammePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const programme = programmes.find(item => item.slug === slug); if (!programme) notFound(); return <main><section className="bg-[#10233f] text-white"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-2 lg:px-8 lg:py-24"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#ffcf24]">{programme.label}</p><h1 className="display mt-5 text-5xl leading-none sm:text-7xl">{programme.title}</h1><p className="mt-7 text-lg leading-8 text-white/75">{programme.short}</p><p className="mt-6 inline-block border border-white/30 px-4 py-2 text-sm font-bold">{programme.duration}</p></div><div className="group relative aspect-[4/3] overflow-hidden"><Image src={programme.image} alt="Communication coaching in progress" fill priority className="object-cover transition duration-700 group-hover:scale-[1.035]" sizes="(max-width: 1024px) 100vw, 50vw" /></div></div></section><section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[0.8fr_1.2fr] lg:px-8 lg:py-28"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#d94b35]">The outcome</p><h2 className="display mt-5 text-4xl leading-tight">{programme.outcome}</h2></div><div><h2 className="text-2xl font-extrabold">What is included</h2><ul className="mt-6 grid gap-4">{programme.included.map(item=><li key={item} className="flex gap-4 border-b border-[#d9d5ca] pb-4 text-lg leading-7"><Check className="mt-1 shrink-0 text-[#d94b35]" size={20}/><span>{item}</span></li>)}</ul><p className="mt-8 leading-7 text-[#626772]">Fees are tailored to your goals, programme length, delivery format and number of participants. We will provide a clear recommendation and quotation after an initial consultation.</p><Link href="/book" className="mt-8 inline-flex items-center gap-3 bg-[#ffcf24] px-6 py-4 font-black text-[#10233f] hover:-translate-y-1 hover:shadow-xl">Discuss your goals <ArrowRight size={18}/></Link></div></section></main>; }
