import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { PageIntro } from "@/components/page-intro";

export const metadata: Metadata = { title: "About", description: "Meet The Speech Factory and founder Jeremiah Kobby Sekyi." };

export default function AboutPage() {
  return <main><PageIntro eyebrow="About us" title="Human communication for a changing world." text="We help leaders communicate clearly, confidently and with impact. Our work combines rigorous thinking, practical coaching and repeated real-world application." />
    <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8 lg:py-28"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#d94b35]">Who we are</p><h2 className="display mt-5 text-5xl leading-none">Ideas matter when people can understand and trust them.</h2><div className="mt-7 grid gap-4 text-lg leading-8 text-[#626772]"><p>AI today can generate content and process information at remarkable speed. Leadership still depends on judgement, empathy, clarity and connection. We are concerned about what happens when, in your greatest challenge, all you have is your mind and voice.</p><p>The Speech Factory exists to strengthen those human capabilities. We help professionals, executives and teams speak with purpose, inspire action and remain relevant in a workplace being reshaped by technology.</p></div></div><div className="group relative aspect-[3/2] overflow-hidden"><Image src="/images/team-culture.webp" alt="The Speech Factory team in conversation" fill className="object-cover transition duration-700 group-hover:scale-[1.035]" sizes="(max-width: 1024px) 100vw, 50vw" /></div></section>
    <section className="bg-[#ffcf24] text-[#10233f]"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-16 md:grid-cols-2 lg:px-8"><article className="border-l-4 border-[#10233f] pl-6"><h2 className="text-sm font-black uppercase tracking-[0.2em]">Our vision</h2><p className="display mt-4 text-3xl leading-tight">A generation of leaders who remain relevant, trusted and influential through human-centred communication.</p></article><article className="border-l-4 border-[#10233f] pl-6"><h2 className="text-sm font-black uppercase tracking-[0.2em]">Our mission</h2><p className="display mt-4 text-3xl leading-tight">Equip leaders with the clarity, confidence and structure to influence outcomes and drive alignment.</p></article></div></section>
    <section className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-[0.8fr_1.2fr] lg:px-8 lg:py-28"><div className="group relative aspect-[2/3] max-h-[720px] overflow-hidden"><Image src="/images/jeremiah-sekyi.webp" alt="Jeremiah Kobby Sekyi" fill className="object-cover object-top transition duration-700 group-hover:scale-[1.035]" sizes="(max-width: 1024px) 100vw, 40vw" /></div><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#d94b35]">Founder and Lead Coach</p><h2 className="display mt-5 text-5xl leading-none sm:text-6xl">Jeremiah Kobby Sekyi</h2><div className="mt-7 grid gap-4 text-lg leading-8 text-[#626772]"><p>Jeremiah is an award-winning public speaker with more than ten years of experience speaking and coaching internationally. He represented his university at more than 50 competitions across six countries and became the first African to win the WUDC public speaking title in 2019.</p><p>His experience includes training professionals and executives from Microsoft, PwC, Deloitte, NEOM and HSBC, alongside workshops for universities, global organisations and emerging leaders.</p><p>Having started as a shy and awkward speaker himself, Jeremiah coaches with the empathy of someone who understands the distance between knowing you have something to say and being able to say it powerfully.</p></div><Link href="/book" className="mt-8 inline-flex items-center gap-2 bg-[#10233f] px-6 py-4 font-black text-white hover:-translate-y-1 hover:shadow-xl">Work with Jeremiah <ArrowRight size={18} /></Link></div></section>
    <section className="bg-[#10233f] text-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#ffcf24]">The team</p><h2 className="display mt-5 max-w-3xl text-5xl leading-none">The people behind every learning experience.</h2><div className="mt-10 max-w-2xl"><article className="group grid overflow-hidden bg-white text-[#131820] sm:grid-cols-[0.8fr_1.2fr]"><div className="relative min-h-80 overflow-hidden"><Image src="/images/susane.webp" alt="Susane, Programme Manager" fill className="object-cover object-top transition duration-700 group-hover:scale-[1.03]" sizes="(max-width: 768px) 100vw, 30vw" /></div><div className="p-7"><p className="text-xs font-black uppercase tracking-[0.18em] text-[#d94b35]">Programme Manager</p><h3 className="mt-3 text-3xl font-extrabold">Susane</h3><p className="mt-5 leading-7 text-[#626772]">Susane helps plan and deliver programmes, coordinates communication and turns learning goals into well-organised workshops and participant experiences.</p></div></article></div></div></section>
    <section className="bg-[#e9e6dc]"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#d94b35]">How we work</p><h2 className="display mt-5 max-w-3xl text-5xl leading-none">Growth requires honesty, practice and purpose.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Growth-oriented","We learn, refine and apply feedback. Participants are supported, challenged and expected to practise."],["Inclusive","We create room for different experiences, starting points and communication styles."],["Purpose-driven","Every programme is built around real outcomes in work, leadership and life."]].map(([title,text],i)=><article key={title} className="bg-white p-7 transition duration-300 hover:-translate-y-1 hover:shadow-xl"><span className="font-black text-[#d94b35]">0{i+1}</span><h3 className="mt-8 text-2xl font-extrabold">{title}</h3><p className="mt-4 leading-7 text-[#626772]">{text}</p></article>)}</div></div></section>
  </main>;
}
