"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowLeft, Check, CheckCircle2, LoaderCircle, CalendarDays, LockKeyhole } from "lucide-react";
import { z } from "zod";
import { coachingNeeds, immediateNeeds, availabilityOptions, urgencyOptions, registrationSchema, PILOT_BOOKING_URL } from "@/lib/pilot";
import styles from "./pilot.module.css";

type FormState={name:string;email:string;contact:string;contactMethod:"Email"|"WhatsApp"|"Phone";nationality:string;timezone:string;needs:string[];goals:string;january:string;urgency:string;immediateNeeds:string[];deadline:string;immediateDetails:string;consent:boolean;updates:boolean;website:string};
const blank:FormState={name:"",email:"",contact:"",contactMethod:"Email",nationality:"",timezone:"",needs:[],goals:"",january:"",urgency:"",immediateNeeds:[],deadline:"",immediateDetails:"",consent:false,updates:false,website:""};
export function PilotSignup(){
 const [data,setData]=useState<FormState>(blank);const [step,setStep]=useState(0);const [errors,setErrors]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [saved,setSaved]=useState(false);const [reference,setReference]=useState("");const [failure,setFailure]=useState("");const requestId=useRef("");const heading=useRef<HTMLHeadingElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{requestId.current=crypto.randomUUID();setData(v=>({...v,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||""}));return()=>{if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:"select_programme_coaching_goals",title:"Select programme coaching goals",description:"Select coaching goals in the January 2027 registration form. This stages choices only and does not submit a registration or grant contact consent.",inputSchema:{type:"object",properties:{needs:{type:"array",items:{type:"string",enum:[...coachingNeeds]},minItems:1,maxItems:8}},required:["needs"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const v=z.object({needs:z.array(z.enum(coachingNeeds)).min(1).max(8)}).strict().parse(input);setData(d=>({...d,needs:[...new Set(v.needs)]}));setStep(1);return{selectedNeeds:v.needs,submitted:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 function field<K extends keyof FormState>(key:K,value:FormState[K]){setData(v=>({...v,[key]:value}));setErrors(v=>({...v,[key]:""}));setFailure("");}
 function toggle(key:"needs"|"immediateNeeds",value:string){field(key,data[key].includes(value)?data[key].filter(x=>x!==value):[...data[key],value]);}
 function validate(current:number){const candidate={...data,requestId:requestId.current,...(current<2?{january:data.january||availabilityOptions[0],urgency:data.urgency||urgencyOptions[2],consent:true}:{})};const parsed=registrationSchema.safeParse(candidate);if(parsed.success)return true;const relevant=current===0?["name","email","contact","contactMethod","nationality","timezone"]:current===1?["needs","goals"]:["january","urgency","immediateNeeds","deadline","immediateDetails","consent"];const next:Record<string,string>={};for(const issue of parsed.error.issues){const key=String(issue.path[0]);if(current===2||relevant.includes(key))next[key]=key==='consent'?"Please agree so we can respond to your registration.":issue.message;}setErrors(next);if(current===2&&Object.keys(next).length){const first=Object.keys(next)[0];if(['name','email','contact','contactMethod','nationality','timezone'].includes(first))setStep(0);else if(['needs','goals'].includes(first))setStep(1);}return Object.keys(next).length===0;}
 function advance(){if(!validate(step))return;setStep(s=>s+1);setTimeout(()=>heading.current?.focus(),0);}
 async function submit(event:React.FormEvent){event.preventDefault();if(step<2){advance();return;}if(!validate(2)||busy)return;setBusy(true);setFailure("");try{const response=await fetch('/api/pilot/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,requestId:requestId.current})});const result=await response.json();if(!response.ok||!result.saved){if(result.fields){const next:Record<string,string>={};Object.entries(result.fields).forEach(([k,v])=>next[k]=(v as string[])[0]);setErrors(next);}throw new Error(result.error||'Your registration could not be saved. Please try again.');}setReference(result.reference);setSaved(true);timer.current=setTimeout(()=>window.location.assign(PILOT_BOOKING_URL),3500);}catch(error){setFailure(error instanceof Error?error.message:'Unable to connect. Please try again.');}finally{setBusy(false);}}
 const err=(key:string)=>errors[key]?<span className={styles.error} id={`error-${key}`}>{errors[key]}</span>:null;
 const inputProps=(key:string)=>({"aria-invalid":!!errors[key],"aria-describedby":errors[key]?`error-${key}`:undefined});
 if(saved)return <div className={styles.success} role="status"><CheckCircle2 size={52}/><p className={styles.eyebrow}>Registration received</p><h3>You’re on our list.<br/><em>Let’s talk next.</em></h3><p>Your details have been saved for The Speech Factory team. We’re opening the calendar so you can choose a consultation time.</p><a href={PILOT_BOOKING_URL} className={styles.button}>Continue to the booking calendar <ArrowRight size={18}/></a><p className={styles.fine}>Your appointment is only confirmed after you finish booking in Google Calendar. Registration does not reserve or pay for a programme place.</p><span className={styles.reference}>Reference: {reference.slice(0,8)}</span></div>;
 return <form onSubmit={submit} noValidate className={styles.form}>
 <ol className={styles.formSteps} aria-label="Registration steps">{["About you","Your goals","Your timing"].map((title,i)=><li key={title} aria-current={i===step?"step":undefined} className={i<=step?styles.activeStep:""}><span>{i<step?<Check size={14}/>:i+1}</span>{title}</li>)}</ol>
 <h3 ref={heading} tabIndex={-1} className={styles.formHeading}>{["First, a little about you.","What would you like to work on?","Let’s make the timing work."][step]}</h3>
 <p className={styles.formIntro}>{["So we can reach you and plan for your time zone. All fields on this step are required.","Choose everything that feels relevant. You do not need to have it all figured out.","The Class of 2027 starts in January. Tell us if you need help before then."][step]}</p>
 {step===0&&<div className={styles.fieldGrid}>
 <label className={styles.full}>Full name<input value={data.name} onChange={e=>field('name',e.target.value)} autoComplete="name" maxLength={120} {...inputProps('name')} placeholder="Your full name"/>{err('name')}</label>
 <label>Email address<input type="email" value={data.email} onChange={e=>field('email',e.target.value)} autoComplete="email" maxLength={200} {...inputProps('email')} placeholder="you@example.com"/>{err('email')}</label>
 <label>Phone / WhatsApp<input type="tel" value={data.contact} onChange={e=>field('contact',e.target.value)} autoComplete="tel" maxLength={40} {...inputProps('contact')} placeholder="Include your country code"/>{err('contact')}</label>
 <label>Preferred contact method<select value={data.contactMethod} onChange={e=>field('contactMethod',e.target.value as FormState['contactMethod'])}><option>Email</option><option>WhatsApp</option><option>Phone</option></select></label>
 <label>Nationality<input value={data.nationality} onChange={e=>field('nationality',e.target.value)} maxLength={100} {...inputProps('nationality')} placeholder="e.g. Ghanaian"/><small>You may enter “Prefer not to say”.</small>{err('nationality')}</label>
 <label className={styles.full}>Time zone<input value={data.timezone} onChange={e=>field('timezone',e.target.value)} maxLength={100} {...inputProps('timezone')} placeholder="e.g. Africa/Accra or UTC+0"/><small>Detected automatically where possible. Please check it.</small>{err('timezone')}</label>
 </div>}
 {step===1&&<><fieldset className={styles.choices}><legend>Coaching needs <span>Choose one or more</span></legend><div>{coachingNeeds.map(need=><label key={need} className={data.needs.includes(need)?styles.chosen:""}><input type="checkbox" checked={data.needs.includes(need)} onChange={()=>toggle('needs',need)}/><span>{need}</span></label>)}</div>{err('needs')}</fieldset><label className={styles.textField}>What would you like to do better?<textarea value={data.goals} onChange={e=>field('goals',e.target.value)} maxLength={1500} rows={4} placeholder="For example: explain my ideas clearly in meetings, speak with confidence, or deliver a stronger presentation." {...inputProps('goals')}/><small>{data.needs.includes('Other')?'Required when you choose Other.':'Optional. A real situation helps us understand your goal.'}</small>{err('goals')}</label></>}
 {step===2&&<>
 <fieldset className={styles.radios}><legend>Are you available to start in January 2027?</legend>{availabilityOptions.map(value=><label key={value}><input type="radio" name="january" value={value} checked={data.january===value} onChange={()=>field('january',value)}/><span>{value}</span></label>)}{err('january')}</fieldset>
 <fieldset className={styles.radios}><legend>Do you need coaching before the programme starts?</legend>{urgencyOptions.map(value=><label key={value}><input type="radio" name="urgency" value={value} checked={data.urgency===value} onChange={()=>{field('urgency',value);if(value===urgencyOptions[2])setData(d=>({...d,immediateNeeds:[],deadline:"",immediateDetails:""}));}}/><span>{value}</span></label>)}{err('urgency')}</fieldset>
 {data.urgency && data.urgency!==urgencyOptions[2]&&<div className={styles.urgentPanel}><p><CalendarDays size={19}/> You don’t have to wait until January to ask.</p><fieldset className={styles.choices}><legend>What support would help sooner?</legend><div>{immediateNeeds.map(need=><label key={need} className={data.immediateNeeds.includes(need)?styles.chosen:""}><input type="checkbox" checked={data.immediateNeeds.includes(need)} onChange={()=>toggle('immediateNeeds',need)}/><span>{need}</span></label>)}</div>{err('immediateNeeds')}</fieldset><label className={styles.textField}>Upcoming date or deadline <span>(optional)</span><input type="date" value={data.deadline} onChange={e=>field('deadline',e.target.value)} {...inputProps('deadline')}/>{err('deadline')}</label><label className={styles.textField}>Tell us what’s coming up <span>(optional)</span><textarea rows={3} value={data.immediateDetails} onChange={e=>field('immediateDetails',e.target.value)} maxLength={1500} placeholder="The interview, speech, presentation or situation you want help with."/></label><small>Any earlier one-to-one coaching is a separate service. We’ll discuss availability and fees before you commit.</small></div>}
 <div className={styles.consent}><label><input type="checkbox" checked={data.consent} onChange={e=>field('consent',e.target.checked)} {...inputProps('consent')}/><span>I agree that The Speech Factory may store my details and contact me about this registration and any coaching support I request. I have read the <Link href="/privacy" target="_blank" rel="noopener noreferrer">Privacy Policy</Link>.</span></label>{err('consent')}<label><input type="checkbox" checked={data.updates} onChange={e=>field('updates',e.target.checked)}/><span>Also send me occasional programme and workshop updates. <small>Optional. You can opt out at any time.</small></span></label></div>
 <p className={styles.fine}>The programme is US$300 for three months. This form registers your interest. No payment is taken and a place is not reserved at this stage.</p>
 </>}
 <div className={styles.honey} aria-hidden="true"><label>Leave this field empty<input tabIndex={-1} autoComplete="off" value={data.website} onChange={e=>field('website',e.target.value)}/></label></div>
 {failure&&<p className={styles.failure} role="alert">{failure}</p>}
 <div className={styles.formActions}>{step>0&&<button type="button" className={styles.backButton} onClick={()=>{setStep(s=>s-1);setErrors({});}} disabled={busy}><ArrowLeft size={16}/> Back</button>}<button className={styles.button} type="submit" disabled={busy}>{busy?<><LoaderCircle size={18} className={styles.spin}/> Saving your registration…</>:step<2?<>Continue <ArrowRight size={18}/></>:<>Save details & continue to booking <ArrowRight size={18}/></>}</button></div>
 <p className={styles.formSecurity}><LockKeyhole size={13}/> Your registration is shared with The Speech Factory team only.</p>
 </form>;
}
