"use client";
import { useCallback, useEffect, useState } from "react";
import { Download, RefreshCw, Inbox, LockKeyhole } from "lucide-react";
import { urgencyOptions, availabilityOptions, type RegistrationRow } from "@/lib/pilot";
import styles from "./pilot.module.css";
export function PilotRegisterAdmin(){
 const [rows,setRows]=useState<RegistrationRow[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");const [filter,setFilter]=useState("all");
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch('/api/pilot/registrations',{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to load the register');setRows(data.registrations);}catch(e){setError(e instanceof Error?e.message:'Unable to load the register');}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 const visible=rows.filter(r=>(filter==='all'||filter==='urgent'&&r.urgency!==urgencyOptions[2]||filter==='january'&&r.january===availabilityOptions[0])&&[r.name,r.email,r.contact,r.nationality,r.needs].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <div className={styles.admin}><div className={styles.adminHeader}><div><p className={styles.eyebrow}><LockKeyhole size={13}/> Team only · Class of 2027</p><h1>The registration book.</h1><p>Contact details, coaching goals and timing, together in one private place.</p></div><div className={styles.adminActions}><button className={styles.textLink} onClick={()=>void refresh()} disabled={loading}><RefreshCw size={15}/> Refresh</button>{!error&&!loading&&<a href="/api/pilot/registrations?format=csv" className={styles.button}><Download size={17}/> Export all to CSV</a>}</div></div>
 {error?<div className={styles.failure} role="alert">{error}</div>:loading?<p role="status">Loading registrations…</p>:<><div className={styles.adminStats}><div><strong>{rows.length}</strong><span>Registrations received</span></div><div><strong>{rows.filter(r=>r.january===availabilityOptions[0]).length}</strong><span>Ready to start in January</span></div><div><strong>{rows.filter(r=>r.urgency!==urgencyOptions[2]).length}</strong><span>Interested in support sooner</span></div></div><div className={styles.adminFilters}><label>Find a registration<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email, contact or coaching need"/></label><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All registrations</option><option value="january">Ready for January</option><option value="urgent">Support before January</option></select></label></div><p className={styles.fine}>CSV exports include every registration and open in Excel or Google Sheets. A submitted form does not confirm a calendar booking. Check the booking calendar separately.</p>
 {visible.length===0?<div className={styles.empty}><Inbox size={30} style={{margin:'auto'}}/><h2>{rows.length?'No matching registrations.':'Ready for the first registration.'}</h2><p>{rows.length?'Try another search or filter.':'Saved form submissions will appear here. The export will use the same records.'}</p></div>:<div className={styles.tableWrap}><table className={styles.table}><caption className="sr-only">Class of 2027 registrations</caption><thead><tr><th>Applicant</th><th>Contact</th><th>Location & timing</th><th>Coaching needs</th><th>Before January</th><th>More details</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{new Date(r.created_at).toLocaleString()}</small><small>Ref: {r.id.slice(0,8)}</small></td><td><a href={`mailto:${r.email}`}>{r.email}</a><br/>{r.contact}<small>Prefers: {r.contact_method}</small></td><td>{r.nationality}<small>{r.timezone}</small><span className={styles.badge}>{r.january}</span></td><td>{JSON.parse(r.needs).join(', ')}</td><td><span className={`${styles.badge} ${r.urgency!==urgencyOptions[2]?styles.urgentBadge:''}`}>{r.urgency}</span>{r.deadline&&<small>Deadline: {r.deadline}</small>}<small>{JSON.parse(r.immediate_needs).join(', ')}</small></td><td><details><summary>Read goals & notes</summary><p><strong>Goals</strong>{r.goals||'No additional goals supplied.'}</p><p><strong>Immediate support</strong>{r.immediate_details||'No further details supplied.'}</p><p>Programme updates: {r.updates?'Opted in':'Not opted in'}</p><p>Contact consent: {r.consent_version}</p></details></td></tr>)}</tbody></table></div>}</>}
 </div>;
}
