export const programmes = [
  { slug: "group-coaching", label: "Enrolling now · Class of 2027", title: "Group Coaching Programme", short: "Our Public Speaking Academy is here. Join the Communication Excellence Programme for three months of group coaching, practical tasks and feedback, starting January 2027.", duration: "Three-month programme · Class of 2027", image: "/images/academy/group-practice.webp", outcome: "Build a repeatable communication practice through live teaching, deliberate practice and direct feedback.", included: ["Weekly live communication sessions", "Practical group coaching and speaking practice", "Weekly tasks and resources", "Monthly speaking projects and feedback", "A completion certificate based on participation and required tasks"] },
  { slug: "executive-coaching", label: "For founders, executives and leaders", title: "Executive One-to-One Coaching", short: "Private, highly tailored support for presentations, leadership communication and high-stakes moments.", duration: "Three to twelve months", image: "/images/executive-coaching.webp", outcome: "Strengthen how you think, structure, deliver and respond when the stakes are high.", included: ["Personal communication diagnostic and coaching plan", "Weekly one-to-one coaching with direct feedback", "Preparation for speeches, meetings, interviews and negotiations", "Custom exercises, resources and between-session practice", "Final evaluation and next-stage development plan"] },
  { slug: "team-training", label: "For organisations and teams", title: "Organisation-wide Training", short: "Bespoke training that strengthens leadership, presentation, collaboration and customer-facing communication.", duration: "Workshops or three to twelve-month programmes", image: "/images/team-training.webp", outcome: "Create shared communication standards that improve alignment, influence and everyday execution.", included: ["Needs assessment and tailored programme design", "Live virtual, in-person or blended delivery", "Practical activities based on real workplace scenarios", "Team practice, coaching and feedback", "Progress review and recommendations for continued development"] },
] as const;

export const testimonials = [
  { quote: "Prior to working with Jeremiah, I struggled with anxiety and confidence. I can now consistently and efficiently articulate my story and my value. I 100% recommend it.", name: "Loren Nelson", role: "CEO, L’avitta Marketing Management", image: "/images/loren-nelson.webp" },
  { quote: "I expected a list of do’s and don’ts, but I got a rigorous deep dive into self-awareness. This course taught me that knowing yourself is the only way to build true confidence.", name: "Michelle De-Veer", role: "Legal Practitioner", image: "/images/michelle-de-veer.webp" },
  { quote: "You shifted all our universes with your guidance today. Spectacular.", name: "Olivia J.", role: "Seismic team workshop participant", image: null },
] as const;
