import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Mic2, MessagesSquare, Presentation, Focus, Zap, Waypoints, Target, Plus } from "lucide-react";
import { Action, ExperienceStrip, Testimonials, FinalInvitation } from "@/components/proof-shared";
import { ReadingProgress } from "@/components/proof-experience";
import styles from "@/components/proof-pages.module.css";

export const metadata: Metadata = {
  title: { absolute: "Executive Communication & Public Speaking Coach | The Speech Factory" },
  description: "Executive communication, public speaking and presentation coaching for professionals, leaders and ambitious communicators. Private and group coaching available online.",
  alternates: { canonical: "https://thespeechfactory.org/executive-communication-coaching" },
  openGraph: { title: "Executive Communication & Public Speaking Coaching", description: "Communicate with clarity when it matters most.", images: [{url:"/images/coach-session.webp",alt:"Jeremiah facilitating a coaching session"}] },
};
const capabilities = [
  [Mic2,"Public Speaking","Build confidence, structure speeches effectively and communicate naturally in front of an audience."],
  [MessagesSquare,"Executive Communication","Bring greater clarity, authority and precision to high-stakes professional conversations."],
  [Presentation,"Presentation Skills","Make your ideas easier to follow, more engaging and more persuasive."],
  [Focus,"Executive Presence","Strengthen vocal delivery, body language, composure and audience connection."],
  [Zap,"Impromptu Communication","Organise your thoughts and respond clearly when there is little time to prepare."],
  [Waypoints,"Persuasive Communication","Develop stronger arguments, explanations and storytelling around your audience."],
  [Target,"Interview & High-Stakes Preparation","Rehearse the interviews, pitches, panels and professional conversations that matter."],
] as const;
const process = [
  ["Diagnosis","Find the friction.","Identify the habits, structural problems or confidence barriers affecting your communication."],
  ["Frameworks","Give ideas a shape.","Learn practical structures for speeches, presentations and responses."],
  ["Deliberate practice","Put it to the test.","Practise under realistic conditions, using the situations you need to handle."],
  ["Feedback","Know what to change.","Get precise feedback on structure, language, delivery and audience connection."],
  ["Repetition","Make it your own.","Apply the feedback and practise again, until better habits feel more natural."],
  ["Real-world application","Take it into the room.","Use the work in your actual presentations, interviews, speeches and meetings."],
];
const faqs = [
  ["Can public speaking actually be learned?","Yes. Structure, preparation, delivery, storytelling, audience analysis and thinking under pressure are trainable skills. Coaching breaks them into components you can deliberately practise and improve."],
  ["Do you provide online public speaking coaching?","Yes. The Speech Factory works with clients online, making coaching accessible to professionals and students in different locations and time zones."],
  ["Is coaching suitable if I’m already a strong speaker?","Yes. Advanced coaching often focuses on precision, persuasion, executive presence, audience adaptation and high-stakes performance, rather than basic confidence."],
  ["Can coaching help with public speaking anxiety?","Coaching can help you develop preparation strategies, greater familiarity with speaking situations and practical techniques for performing under pressure. The aim is to communicate effectively even when you feel nervous."],
  ["How does executive communication differ from public speaking?","Public speaking focuses primarily on communicating in front of an audience. Executive communication also covers leadership, meetings, stakeholder conversations, presentations, interviews and other professional situations."],
  ["Do you provide corporate communication training?","Yes. We can tailor workshops and communication training to an organisation’s audience, priorities and day-to-day communication challenges."],
  ["How is coaching structured?","The format depends on your goal. We can work towards a defined event or challenge, or build a longer development plan combining diagnosis, frameworks, deliberate practice, feedback and repetition."],
  ["What happens in the first consultation?","We discuss your communication goal, the situations that matter most, current barriers, your timeline and the support you need. The aim is a clearer understanding of what to work on and whether our coaching is a good fit."],
];
export default function CoachingPage(){return <main className={styles.page}>
  <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: "{\"@context\":\"https://schema.org\",\"@type\":\"WebPage\",\"name\":\"Executive Communication & Public Speaking Coaching\",\"url\":\"https://thespeechfactory.org/executive-communication-coaching\",\"isPartOf\":{\"@type\":\"WebSite\",\"name\":\"The Speech Factory\",\"url\":\"https://thespeechfactory.org/\"}}" }}/><ReadingProgress/>
  <section className={styles.serviceHero}><div className={`${styles.wrap} ${styles.serviceHeroGrid}`}><div><Link href="/proof-of-work" className={styles.breadcrumb}>Proof of Work <span>/</span> Communication Coaching</Link><p className={styles.eyebrow}>Private coaching · Group programmes · Team training</p><h1>Executive Communication<br/>& <em>Public Speaking</em><br/>Coaching</h1><p className={styles.serviceLead}>Communicate with clarity when it matters most.</p><p>Intensive coaching for professionals, leaders and ambitious communicators. Turn what you know into what people understand, remember and act on.</p><div className={styles.heroActions}><Action href="/book" event="communication_consultation_click">Book a Communication Consultation</Action><Action href="#corporate-training" secondary event="corporate_training_click">Discuss Corporate Training</Action></div></div><div className={styles.servicePortrait}><Image src="/images/coach-session.webp" alt="Jeremiah Kobby Sekyi leading a live communication coaching session" fill priority sizes="(max-width: 900px) 90vw, 40vw"/><div className={styles.portraitNote}><span>Not just knowing what to say.</span><strong>Being able to say it.</strong></div><span className={styles.portraitCaption}>Jeremiah Kobby Sekyi · Founder & Lead Coach</span></div></div><div className={`${styles.wrap} ${styles.serviceProof}`}><span><strong>2,000+</strong> students & professionals trained</span><span><strong>10+ years</strong> of our founder’s speaking & coaching experience</span><Link href="/proof-of-work" data-analytics-event="service_to_proof_click">See the work behind the words <ArrowUpRight size={17}/></Link></div></section>
  <ExperienceStrip/>
  <section className={`${styles.wrap} ${styles.section}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>The professional advantage</p><h2>You know your work.<br/><em>Help people see it.</em></h2></div><p>Present an idea. Lead a meeting. Explain something complex. Answer the question you didn’t expect. Communication is the skill that helps your other skills be recognised.</p></div><div className={styles.capabilities}>{capabilities.map(([Icon,title,copy],i)=><article className={styles.capability} key={title} data-reveal><div><Icon size={26} strokeWidth={1.3}/><span>0{i+1}</span></div><h3>{title}</h3><p>{copy}</p></article>)}<Link href="/book" className={styles.capabilityCta}><span>Where do you want<br/>to make progress?</span><strong>Let’s find your starting point.</strong><ArrowUpRight size={34}/></Link></div></section>
  <section className={styles.method}><div className={styles.wrap}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>How the work happens</p><h2>Confidence isn’t a script.<br/><em>It’s a practice.</em></h2></div><p>Frameworks give you a starting point. Practice, feedback and repetition turn that knowledge into something you can use when it counts.</p></div><ol className={styles.process}>{process.map(([name,title,description],i)=><li key={name} data-reveal><span className={styles.processNumber}>0{i+1}</span><p className={styles.micro}>{name}</p><h3>{title}</h3><p>{description}</p></li>)}</ol><Action href="/book" event="communication_consultation_click">Find your coaching focus</Action></div></section>
  <section className={`${styles.wrap} ${styles.section} ${styles.audience}`}><div><p className={styles.eyebrow}>Who this is for</p><h2>For the moments<br/><em>that ask more of you.</em></h2><p>Executives, founders, managers, consultants, client-facing professionals, students and emerging leaders. Wherever you are starting, we build around the situations you need to navigate.</p><p className={styles.online}><span/> Available online, across locations and time zones.</p></div><div className={styles.audienceScenarios}><p><span>01</span> You’re stepping into leadership.</p><p><span>02</span> Your ideas need a clearer voice.</p><p><span>03</span> An important presentation is coming.</p><p><span>04</span> Nerves are getting in the way.</p><p><span>05</span> Your team needs to communicate better.</p></div></section>
  <section className={styles.depth}><div className={styles.wrap}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Choose your focus</p><h2>The right work.<br/><em>For your real world.</em></h2></div><p>We shape the format around your goal, whether that means preparing for one important moment or developing a lasting professional skill.</p></div><div className={styles.serviceDetails}>
    <article id="executive-coaching"><div className={styles.serviceNumber}>01</div><div><h2>Executive Communication Coaching</h2><p>Leadership asks you to make complex ideas clear, bring people with you and remain composed when the questions get difficult. Private coaching helps you sharpen your message and strengthen how you deliver it.</p><details><summary>Explore the coaching focus <Plus size={18}/></summary><p>Work on board and stakeholder presentations, concise updates, leadership storytelling, persuasion, meeting contributions, vocal delivery and high-pressure Q&A. Bring an upcoming speech, interview or professional conversation, or work through a longer development plan.</p></details><Action href="/programmes/executive-coaching" secondary>Explore executive coaching</Action></div></article>
    <article id="public-speaking"><div className={styles.serviceNumber}>02</div><div><h2>Public Speaking Coaching</h2><p>You do not need to eliminate every nerve to speak well. You need a clear structure, purposeful preparation and enough practice to stay connected to your audience.</p><details><summary>Explore the coaching focus <Plus size={18}/></summary><p>Build stronger openings and endings, develop storytelling, use your voice and body intentionally, organise impromptu responses and handle audience questions. Rehearse effectively without relying on word-for-word memorisation.</p></details><Action href="/programmes/group-coaching" secondary>Explore group coaching</Action></div></article>
    <article id="presentation-coaching"><div className={styles.serviceNumber}>03</div><div><h2>Presentation Skills Coaching</h2><p>A good presentation makes the important idea easy to follow. We help you find that idea, build the story around it and deliver it with purpose.</p><details><summary>Explore the coaching focus <Plus size={18}/></summary><p>Work on explaining data and complex information, creating a compelling opening, balancing slides with your spoken message, adapting to your audience and preparing for Q&A. Use an actual presentation to rehearse and refine both the story and the delivery.</p></details><Action href="/book" secondary event="communication_consultation_click">Prepare your next presentation</Action></div></article>
    <article id="corporate-training"><div className={styles.serviceNumber}>04</div><div><h2>Corporate Communication Training</h2><p>Equip your team to present, collaborate and represent your organisation with greater clarity. Training starts with the communication challenges your people actually face.</p><details><summary>Explore formats and focus areas <Plus size={18}/></summary><p>Choose tailored workshops or longer programmes around leadership, presentations, client communication, storytelling, persuasion, impromptu speaking, executive presence, difficult conversations, interviews or pitching. Delivery can be online, in person or blended, depending on your needs.</p></details><Action href="/book" secondary event="corporate_training_click">Discuss Corporate Training</Action></div></article>
  </div></div></section>
  <section className={`${styles.wrap} ${styles.section}`}><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Experience, not just promises</p><h2>See what the work<br/><em>can mean to someone.</em></h2></div><Action href="/proof-of-work" secondary event="service_to_proof_click">See selected work and outcomes</Action></div><Testimonials compact/><div className={styles.founder}><div className={styles.founderImage}><Image src="/images/jeremiah-sekyi.webp" alt="Jeremiah Kobby Sekyi, founder of The Speech Factory" fill sizes="(max-width: 700px) 90vw, 250px"/></div><div><p className={styles.eyebrow}>Meet your lead coach</p><h3>Jeremiah Kobby Sekyi</h3><p>An award-winning public speaker with more than a decade of international speaking and coaching experience. In 2019, Jeremiah became the first African to win the WUDC public speaking title. His approach combines deliberate practice with the empathy of someone who started as a shy speaker himself.</p><Action href="/about" secondary>Meet the people behind the work</Action></div></div></section>
  <section className={styles.faqSection}><div className={`${styles.wrap} ${styles.faqGrid}`}><div><p className={styles.eyebrow}>A little more clarity</p><h2>Frequently<br/><em>asked questions.</em></h2><p>Something else on your mind?</p><Action href="/contact" secondary>Talk to our team</Action></div><div className={styles.faqs}>{faqs.map(([q,a])=><details key={q}><summary><h3>{q}</h3><Plus size={20}/></summary><p>{a}</p></details>)}</div></div></section>
  <FinalInvitation/>
</main>;}
